# Generated by Django 4.0 on 2022-01-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_pieces', models.CharField(default='white', max_length=6)),
                ('fen', models.CharField(blank=True, max_length=100, null=True)),
                ('pgn', models.TextField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(default=1)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='auth.user')),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='auth.user')),
            ],
        ),
    ]
