# Generated by Django 4.0 on 2022-01-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='auth.user'),
        ),
    ]
