# Generated by Django 4.0 on 2022-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_alter_game_opponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='host_pieces',
        ),
        migrations.AddField(
            model_name='game',
            name='host_white',
            field=models.BooleanField(default=True),
        ),
    ]
