# Generated by Django 4.0 on 2022-01-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_remove_game_host_pieces_game_host_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(1, 'Game created'), (2, 'Game in progress'), (3, 'Game completed')], default=1),
        ),
    ]
